# handlers file for ansible-nftables
---
- name: restart nftables
  become: true
  ansible.builtin.service:
    name: "nftables"
    state: restarted

- name: reload nftables
  become: true
  ansible.builtin.service:
    name: "nftables"
    state: reloaded
